### ISSUE TITLE
Unable to get repose

### ISSUE THREAD

**Issue by natiwho** [chroxify/namegpt#1]
I followed the readme instruction however I was not able to get the repose I gave it the prompt.
I get this error message instead
![image](https://user-images.githubusercontent.com/66393884/229408278-8a95c981-c035-41f0-9c41-2115367429bf.png)

**Comment by chroxify** [comment]
Hi, are you sure that you have entered a correct api key in your `.env` file?

**Comment by chroxify** [comment]
@NatnaelGebremichael let me know, would otherwise close the issue.
